### ISSUE TITLE
Removing need for semicolons

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#104]
Make semicolons redundant if possible, although this needs further discussion as it has the following consequences:

1) Can no longer sensibly have multiple statements on one line.
2) Error recovery becomes more difficult.
3) Some error messages are more difficult to identify.

Whilst semicolons have proven problematic with learners, it seems they get used to the idea after only a short period.

**Comment by knicos** [comment]
Semicolons will be replaced by line breaks OR commas, allowing multiple statements on one line. Reasoning: "with" statements will need to become a list of override statements(!) to allow for "is" and "=" distinction. To obtain a function like syntax a comma would make more sense.

The resulting various combinations of "with" statements would be:

```
mypoint is Point{x=5,y=10}
mypoint is Point with x=5, y=10
mypoint is Point with {x=5,y=10}
mypoint is Point with {
    x = 5
    y = 10
}
mypoint is Point with
    x = 5,
    y = 10
```

**Comment by ElizabethHudnott** [comment]
So how will we write statements that extend longer than one line?  E.g.

x is f("This is a very long string.
    It extends onto more than one line
");

Some languages use a line ending with a backslash to indicate line continuation, though I don't know if perhaps it's possible to do it without a special character and still eliminate semi-colons?

**Comment by knicos** [comment]
Good point. Its possible for the parser to work without any kind of statement separator, but this hugely reduces its ability to detect errors and would make the code much harder to read (difference between multi-line statement and another statement will not be so obvious).

Another possibility: enforce indentation rules?

**Comment by ElizabethHudnott** [comment]
Personally, with the strings scenario, I always indent (which of course means that I end up with superfluous tab characters embedded in the string but most often the context is HTML so it doesn't matter).  So, in this case, using indentation rules would be an improvement.

However, there are many cases to consider, including situations where people's ideas about the "correct" level of indentation will vary.  For example, if I break up a complicated if condition onto multiple lines then how much indentation is required?  What about if I want to use extra indentation to clarify parentheses (e.g. nested && within ||, etc.)?

if (a ||
    (b && c &&
       d) ||
    e) {
    ##do something
}

It becomes quite complicated.

Also, what if some people use spaces instead of tabs?  How many spaces are required?

I feel that indentation rules are a "neat" solution but also can be a hassle because it becomes more rules to learn.  It's probably one of those, "EM is supposed to allow for being messy", things.  Our workflow patterns aren't as rigid as that of Haskell or Python programmers.

Seems like a backslash to continue a line is probably the easiest to work with, and the easiest to teach (assuming that we're agreed that the other option that required trashing error recovery is a no-go area).

**Comment by knicos** [comment]
Agreed. Indentation was just a suggestion, I'm glad we think the same way about it. Since switching to \ new lines is just as confusing as ; statements, I'd argue in favour of not making the change at all then. I'll allow ; or comma to separate statements, with the last statement not requiring either (but can optionally have).

**Comment by ElizabethHudnott** [comment]
You mean the last statement on a line won't require a semi-colon?  I thought that made error detection difficult when multi-line statements are allowed?  Or the last statement in a block?

**Comment by knicos** [comment]
last in a block

**Comment by ElizabethHudnott** [comment]
But multi-line statements are much, much rarer than having multiple statements.  The former is an experienced user thing that many students don't even think about trying, whereas the latter is kind of essential.  I think it's worth making the change even if there is some penalty attached regarding making multi-line statements harder.

**Comment by knicos** [comment]
I think we need more than 2 opinions :/

**Comment by knicos** [comment]
Also, when "with" is used properly I suspect multi-line statements will become more common.

**Comment by ElizabethHudnott** [comment]
Yes.  Though your original suggestion allowed each override to be on a new line, which seems to me to be the place where I'd most often be wanting to put a new line.  Or do you think there will be a lot of additional new lines in other places too?

**Comment by knicos** [comment]
If you want to do:

```
mypoint is Point with {
    x = 5,
    y = 10
}
```

then no problem. But:

```
mypoint is Point with \
{
...
```

is a problem, as is the reduced bracket version:

```
mypoint is Point with \
    x = 5, ....
```

So are multi part if's which would probably happen more if you are using scoping for functions...

myif is x if y \
    else z if w \
    else p

I'm just not sure. Separating statements makes sense (and in some cases will be wanted when they are on the same line), adding extra characters in the middle of statements seems less appealing to me.

**Comment by knicos** [comment]
Done
