### ISSUE TITLE
Improved "for" loop syntax

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#107]
Find a better and more modern syntax for "for" loops. This should ideally match the syntax used for range scoping.

```
for x = 1..10 {}
```

```
for x in someList {}
```

```
for x = 1..10 step 2 {}
```

**Comment by ElizabethHudnott** [comment]
Yes, consistency in syntax is strongly desirable.

I still think we can go further with our words instead of symbols idea (though not too far, e.g. + remains a fine operator name!).  I'm an advocate for:

for x = 1..10
  ##do stuff
end for

(In my experience (of programming in general) it's useful when having nested blocks of different types to be able to see which end belongs to which beginning in a long piece of code.)

**Comment by knicos** [comment]
possibly. although bracket matching might help a little. I'm worried this will make the language too verbose.

**Comment by ElizabethHudnott** [comment]
But look!  I took Pascal's syntax and eliminated the word "begin" to be less verbose and compensate for adding the word "for" :)

I think it's okay.

Bracket highlighting helps, but not when the block is so long that it doesn't fully fit into the edit window.

I think (considering we are about a language for learning) being ever so slightly on the side of being too verbose is better than being too obtuse.  If we add autocomplete then we can autocomplete on typing the word "end" anyway.

**Comment by knicos** [comment]
I think I'm for single keywords at a time rather than "end for". Certainly don't want "rof" thought :). But I'll keep my mind a bit open on this one for now and play with some options.

**Comment by ElizabethHudnott** [comment]
Curious as to why impose such a limitation on oneself?

Oh, Unix shell, how we love you...

**Comment by knicos** [comment]
Done
