### ISSUE TITLE
Circle with negative radius

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#120]
Circles with a negative radius cause exceptions. We need to fail silently here.

**Comment by ElizabethHudnott** [comment]
At the moment the exception is caught and ignored (unless you have the debugging preference option enabled, in which case (and should be only this case) you will be thrown into the debugger).  I can make it more silent if you wish.

There is currently very little error checking performed on any of the drawables.  For instance, if you set a radius of "red" then you don't receive any error.  This is because the error log window is so in your face in master that generating an error every time some other parameter supplied to Circle changes (thus causing re-evaluation of the circle) would be incredibly intrusive!  We need to find a way of collecting together similar errors and only reporting them once.  Perhaps the new input window already handles this?  Or do I need to rework the way that the library raises errors?  Thoughts spring to mind again about the benefits of having the maintainer check types instead of the library runtime doing it.

Anyway, I agree that negative radii should be silently ignored.  But I think "red" (radius parameter accidentally missed out) should be flagged as an error.  Unfortunately, I think you will find many, many examples like negative circle radius (and the "red" radius) in the current code because nobody has ever systematically thought about the possible errors that a user can make when defining drawables due to the fact that often there weren't appropriate ways of signalling these errors anyway because of the poor system architecture for signalling errors (as described above).

**Comment by knicos** [comment]
My main concern really was in the Malaria model. If I have the console open it generates so many DOMExceptions that my browser almost halts completely.

My input window only catches exceptions relating to the direct execution of the script. Errors occurring in later definition evaluations get thrown to a little popup status box at the top which isn't so in-your-face. I believe I've adjusted this in EdenUI so just throwing normal eden errors now doesn't display the old error window.

**Comment by ElizabethHudnott** [comment]
Okie.  Coincidentally, last night I started working on a collection of little fixes for drawable related glitches, so I've fixed the Circle problem locally on my machine but haven't yet finished a few other things.  I can send you the Circle thing on it's own if you need it immediately.

**Comment by knicos** [comment]
Nah, its ok, I've got TONS of other stuff to do anyway... will wait.
