### ISSUE TITLE
The JSPE window is missing a scrollbar

### ISSUE THREAD

**Issue by meurigbeynon** [EMGroup/js-eden#161]
A JSPE slide should ideally be short enough to fit on the screen without difficulty. When developing large presentations / stream-of-thought records (such as is lilustrated  in the MENACE construal), it can be hard to avoid extended script fragments. Without a scroll bar he only way to enter these is to zoom out on the browser, but this may make them virtually unreadable.

**Comment by ElizabethHudnott** [comment]
Ermm... yes indeed!  There's not been an conscious move to remove the scroll bar that I know of.  Tested in classic branch and the scroll bar is still there perfectly fine.  But it's been assigned to me so will certainly try to look into it when I can.

**Comment by knicos** [comment]
I think I removed it when making mario because scrolling makes no sense in that context. It needs to be controllable.

**Comment by ElizabethHudnott** [comment]
I don't think HTML content should ever render outside the bounds of the canvas, a situation that used to cause scroll bars to appear on account of the HTML content out of view while simultaneously any canvas shapes were clipped to the proper area.  Usually this "HTML element off canvas" behaviour was wrong but harmless.  Indeed, it seems the JSPE relied on this anomalous behaviour!  I don't know about the situation with Mario.  I didn't think it used HTML ( ? )

I've now fixed the JSPE by putting the scroll bar on the < div > containing the slide text instead of the canvas.  This has the added benefit that it is no longer necessary to scroll up to reach the previous and next buttons.

However, Nick's "fix" for Mario has broken the zoom functionality.  There should be scroll bars present when the canvas is zoomed in, so that you can pan around.  No wonder my instructions about using zoom last week made little sense.

So the JSPE is fixed but the underlying issue requires further work.  Going to have to sleep on this one and try again another day.

**Comment by knicos** [comment]
Lol. I should think panning when zoomed shouldn't use visible scroll bars? I don't see google maps etc using scroll bars. Anyway, at default zoom I don't think canvas should scroll so my fix fixed something, I wasn't using HTML and it was still scrolling because I wanted to get rid of the border between the canvas and the edge of the dialog.

**Comment by ElizabethHudnott** [comment]
Google Maps on the desktop seems to require a dragging motion to pan.  But some construals use dragging for their own purposes.  The touchpad scrolling gesture only seems to work when the scroll bars are visible and not everybody is necessarily using a machine with a touchpad anyway.  I find that Google Maps' behaviour in this regard has become non-standard and confusing in a modern gesture rich environment.
