### ISSUE TITLE
Clicking in the gutter of a proc doesn't execute it

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#175]
There seems to be an inconsistency between actions and procs which is proving very confusing.

**Comment by knicos** [comment]
This is intentional. Procs are very different things to actions... the execution of actions does all the statements, the gutter execution of procs puts the proc in the symbol table. It cannot be any other way because how else do procs get put in the symbol table? Or do they get put in the symbol table and executed immediately (seems wrong).
