### ISSUE TITLE
SymbolViewer and long lists?

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#176]
Is there anything we can do to help with this? Atm, I'm using the new scriptview inspect mode because at least I can scroll it to see the whole list effectively.

**Comment by ElizabethHudnott** [comment]
Maybe something like how the JavaScript console writes them?  I.e. just write a long list as [...] with an arrow that when clicked expands the elements vertically. Probably not a quick change to make though.

Object types can already return a different string for their toString method (used by Eden.prettyPrintValue, used by the symbol viewer) to the string that their getEdenCode method returns.  PixelList and GreyPixelList exploit this difference to write a summary like "20000 pixels" instead of writing out the RGB values for 20,000 pixels (which originally crashed the symbol viewer when PixelList was first tested!).
