### ISSUE TITLE
Make search behaviour consistent across window types

### ISSUE THREAD

**Issue by itsmonktastic** [EMGroup/js-eden#51]
Every search bar should accept a regex, there should be no implicit ^.

**Comment by ElizabethHudnott** [comment]
Definitely should be consistent, though I'm having second thoughts on what the solution should be and I am now leaning towards trying to make things more accessible for beginners (including non-computer experts) who've never heard of regular expressions.

Although on the face of it the following sounds rather complicated, having experimented a little I think that something like the following rules work well in practice for trying to "intelligently" interpret the user's intentions.

(1) If the search string is less than 4 characters long and doesn't contain any regular expression meta characters then it should be automatically anchored to the the beginning of the string, otherwise it shouldn't.  Justification: when a beginner (or even I) types "i" they expect identifiers beginning with i to be shown, but they don't expect "Circle" to appear.  Four letters is about the threshold at which what they've typed is likely to form a natural language noun, verb, adjective or adverb and related identifiers could share the same word at different positions within the string and a beginner won't be expecting that they have to type .* to un-anchor themselves from the beginning of the string.  Shorter than 4 letters is probably some sort of identifier prefix.  Whether the threshold should be 3 or 4 characters warrants some further experimentation.

(2) If the search string contains a capital letter then the search should be case sensitive, otherwise it shouldn't be.  Justification: If the user went to the extra effort of holding down the shift key then they probably meant it.  But if there are no capital letters present then we simply don't know.  Maybe the user doesn't know that searches can be case sensitive, or maybe an advanced user simply forgot that they'd used both upper and lower case versions of the same word in the their construal.
